parser: "@typescript-eslint/parser"
extends:
  - plugin:prettier/recommended
  - prettier
  - eslint:recommended
plugins:
  - "@typescript-eslint"
  - unused-imports
parserOptions:
  sourceType: module
  project: tsconfig.json
env:
  es6: true
  node: true
rules:
  linebreak-style: 0
  no-var: error
  semi: error
  indent: "off"
  no-multi-spaces: error
  space-in-parens: error
  no-multiple-empty-lines: error
  prefer-const: error
  unused-imports/no-unused-imports: warn
